# 1. Chọn môi trường nền (Base Image)
FROM node:20-alpine

# 2. Thiết lập thư mục làm việc bên trong container
WORKDIR /app

# 3. Copy file cấu hình thư viện vào trước
COPY package*.json ./

# 4. Cài đặt các thư viện (node_modules)
RUN npm install

# 5. Copy toàn bộ code còn lại vào (để dự phòng)
COPY . .

# 6. Thông báo port sẽ dùng
EXPOSE 4200

# 7. Lệnh chạy server khi container khởi động
CMD ["./node_modules/.bin/ng", "serve", "frontend", "--host", "0.0.0.0", "--poll", "2000", "--allowed-hosts=all"]
